name: Say hola
run-name: Proceso para ejecutar hola mundo
on:
  push:
    branches:
      - main
 
jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar el mensaje
        run: echo "¡Hola mundo!"
        